---

stages:
  - test

ansible-lint:
  image: supsy/molecule-systemd:base-ansible6
  variables:
    PY_COLORS: 1
    GIT_CLONE_PATH: $CI_BUILDS_DIR/phpfpm
  stage: test
  before_script:
    - ansible-lint --version
  script:
    - ansible-lint .

molecule:
  image: supsy/molecule-systemd:base-ansible6
  services:
    - docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
    GIT_CLONE_PATH: $CI_BUILDS_DIR/phpfpm
  stage: test
  script:
    - molecule test
  parallel:
    matrix:
      - MOLECULE_OS:
          - debian9
          - debian10
          - "ubuntu20.04"
          - "ubuntu22.04"
        MOLECULE_PLAYBOOK:
          - converge
          - converge_additional-phpvalues
  tags:
    - docker
