---
# tasks file for roles/phpfpm

- name: Include meta vars
  ansible.builtin.include_vars:
    file: meta/main.yml
    name: meta

- name: Verify OS compatibility
  ansible.builtin.assert:
    that:
      - ansible_distribution_release in (meta.galaxy_info.platforms | selectattr('name', 'search', ansible_distribution) | first).versions
    success_msg: "{{ ansible_distribution }} {{ ansible_distribution_release }} ({{ ansible_os_family }})"
    fail_msg: "{{ ansible_distribution }} {{ ansible_distribution_release }} ({{ ansible_os_family }}) not supported by Role!"

- name: Add the OS specific variables
  ansible.builtin.include_vars:
    file: "{{ item }}"
  when: lookup('fileglob', "vars/" ~ item, wantlist=True, errors='ignore') | length > 0
  loop:
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_distribution }}/{{ ansible_distribution_release }}.yml"

- name: Verify required version parameter
  ansible.builtin.assert:
    that:
      - phpfpm__version
      - phpfpm__version in phpfpm__supported_versions
    fail_msg: PHP FPM version not defined or not supported!

- name: Verify required parameters
  ansible.builtin.assert:
    that:
      - phpfpm__pools
    fail_msg: Required parameters not set! Please check README for required parameters!

- name: Include task install
  ansible.builtin.include_tasks: install.yml

- name: Include task fpm_pools
  ansible.builtin.include_tasks: config/fpm_pools.yml

- name: Include task fpm_php_config
  ansible.builtin.include_tasks: config/php.yml

- name: Start and enable {{ phpfpm__service_name }}
  ansible.builtin.service: 
    name: "{{ phpfpm__service_name }}"
    state: started
    enabled: yes