---
# vars file for roles/phpfpm pools

- name: Config | fpm_pools | Create php fpm pool
  ansible.builtin.include_tasks: fpm_pool.yml
  loop: "{{ phpfpm__pools }}"

- name: Config | fpm_pools | Remove preinstalled php fpm pool
  ansible.builtin.file:
    path: '{{ phpfpm__server_app_path }}/pool.d/www.conf'
    state: absent
  notify: 'Restart php{{ phpfpm__version }}-fpm'
