---
- name: Converge
  hosts: all
  
  roles:
    - role: phpfpm
      vars:
        phpfpm__version: '7.3'
        phpfpm__pools:
          - name: default
            additional_php_admin_values:
              max_execution_time: 300
