---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "${MOLECULE_OS:-debian10}"
    image: "supsy/molecule-systemd:${MOLECULE_OS:-debian10}"
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
      - /run/lock
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge}.yml
  config_options:
    diff:
      always: true
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: True
    ssh_connection:
      pipelining: True
verifier:
  name: ansible
