---
- name: Prepare
  hosts: all

  tasks: 
    - name: Create vhost logs directory
      file:
        path: '/var/www/vhosts/default/logs/'
        owner: root
        group: root
        mode: '0755'
        state: directory
    - name: Install required packages for debian not installed in docker
      apt: 
        name: ['gpg', 'apt-transport-https']
        update_cache: yes
        state: present
      when: ansible_os_family == 'Debian'
